-- 1. setup
DROP TABLE accounts;

CREATE TABLE accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  balance DEC(15, 2) NOT NULL
);

INSERT INTO accounts (name, balance) VALUES('Bob', 10000);

BEGIN;
INSERT INTO accounts(name, balance) VALUES('Alice', 10000);
-- transaction won't be saved across sessions unless I commit
COMMIT;

TABLE accounts;

-- 2. transfer and commit
BEGIN; 
  UPDATE accounts SET balance = balance - 1000 WHERE name = 'Bob';
  UPDATE accounts SET balance = balance + 1000 WHERE name = 'Alice';
  TABLE accounts;
COMMIT;

-- 3. transfer and rollback
INSERT INTO accounts(name, balance) VALUES('Jack', 0);

BEGIN;
  UPDATE accounts SET balance = balance - 1500 WHERE id = 1;
  UPDATE accounts SET balance = balance + 1500 WHERE id = 3; -- mistake
  TABLE ACCOUNTS;
ROLLBACK;
  TABLE ACCOUNTS;
